input {
  beats {
    port => 5044
  }
}
filter {
  if [log_source] == "suricata" {
    json {
      source => "message"
    }
    if [event_type] != "alert" {
      drop { }
    }
    if [src_ip] {
      mutate {
        add_field => { "[attacker][ip]" => "%{[src_ip]}" }
      }
    }
    if [alert][signature] {
      mutate {
        add_field => { "[detection][message]" => "%{[alert][signature]}" }
      }
    }
  }
  else if [log_source] == "modsecurity" {
    json {
      source => "message"
    }
    if "_jsonparsefailure" in [tags] {
      drop { }
    }
    if [transaction][client_ip] {
      mutate {
        add_field => { "[attacker][ip]" => "%{[transaction][client_ip]}" }
      }
    }
    if [transaction][messages][0][message] {
      mutate {
        add_field => { "[detection][message]" => "%{[transaction][messages][0][message]}" }
      }
    }
  }
}
output {
  #elasticsearch {
  #  hosts => ["localhost:9200"]
  #  index => "waf-suricata-logs-%{+YYYY.MM.dd}"
  #}
  stdout {
    codec => rubydebug
  }
}
